### ISSUE TITLE
在Github上部署一个页面

### ISSUE THREAD

**Issue by zyshin** [ai-writing/Front-End#1]
看起来这个项目是全静态的，可以利用Github的静态页面host功能，方便demo和讨论，见 https://pages.github.com

**Comment by jszh** [comment]
似乎这样无法和当前的项目保持同步，因为需要人工编译，要新开一个 repo 手动操作

**Comment by jszh** [comment]
目前通过 https://github.com/X1011/git-directory-deploy 的脚本进行部署

**Comment by zyshin** [comment]
前端不是全静态文件吗？为啥还要编译？我记得Github有自动化部署的功能，只要push代码就自动执行更新

**Comment by jszh** [comment]
我理解，用 vue 不是直接写的 HTML/JS/CSS 文件，需要 npm 来 build。现在已经基本解决了，只要开发的时候运行一个脚本就能更新。已经部署在 https://ai-writing.github.io/Front-End/

**Comment by zyshin** [comment]
不错，就是这个意思！Vue需要build的话那感觉其实也不能WSWG地开发调试？

**Comment by jszh** [comment]
Flask 框架提供了一个 Server，可以用来本地开发调试，把 build 好的文件放到目录里就行。

**Comment by zyshin** [comment]
https://ai-writing.github.io/Front-End/ 也需要一个Server，我看目前调用的是 https://ai-writing.github.io/api/num ，可是 github.io 允许运行Python动态Server吗？

**Comment by jszh** [comment]
我想这个只能部署在服务器了

**Comment by zyshin** [comment]
嗯，那就部署到服务器吧
